version: 2.1
executors:
  builder:
    environment:
      APP_NAME: libpostal-rest
    working_directory: ~/code
    docker:
      - image: eu.gcr.io/bulbenrg/builder:node12
        auth:
          username: _json_key
          password: $GCP_SERVICE_KEY

jobs:
  build_n_push:
    executor: builder
    environment:
      SKIP_CONFIG_CHECK: "true"
    steps:
      - checkout
      - run:
          name: Authenticate with Google Cloud
          command: ./.circleci/gcloud-auth.sh
      - setup_remote_docker
      - run:
          name: Build image
          command: docker build -t libpostal-rest -t eu.gcr.io/bulbenrg/libpostal-rest .
      - run:
          name: Push to registry
          command: docker push eu.gcr.io/bulbenrg/libpostal-rest
  deploy:
    executor: builder
    parameters:
      namespace:
        type: string
    steps:
      - checkout
      - run:
          name: Authenticating with Google Cloud
          command: ./.circleci/gcloud-auth.sh
      - run:
          name: Deploying to << parameters.namespace >>
          command: kubectl apply -f k8s/manifest.yml -n << parameters.namespace >>
      - run:
          name: Awaiting rollout
          command: kubectl -n << parameters.namespace >> rollout status deploy libpostal

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - approve_build_n_push:
          type: approval
      - approve_staging_deploy:
          type: approval
      - approve_prod_deploy:
          type: approval
          filters:
            branches:
              only: master

      - build_n_push:
          context: bulbenrg-default
          requires:
            - approve_build_n_push

      - deploy:
          name: deploy_staging
          namespace: default
          context: bulbenrg-default
          requires:
            - approve_staging_deploy

      - deploy:
          name: deploy_prod
          namespace: prod
          context: bulbenrg-default
          requires:
            - approve_prod_deploy
          filters:
            branches:
              only: master
